"use client";

import { useState, useRef, useEffect, useCallback } from "react";
import { usePathname } from "next/navigation";
import { streamHelpChat } from "@/lib/api";
import { cn } from "@/lib/utils";
import {
  HelpCircle, X, Send, ChevronDown, ChevronRight,
  Zap, Inbox, BarChart3, Settings, Eye, MessageSquare,
  BookOpen, Search,
} from "lucide-react";

// ── Guide content ─────────────────────────────────────────────────────────────

interface GuideSection {
  icon: React.FC<{ className?: string }>;
  title: string;
  items: { q: string; a: string }[];
}

const GUIDE: GuideSection[] = [
  {
    icon: ({ className }) => <Zap className={className} />,
    title: "Getting started",
    items: [
      {
        q: "What is Vantage?",
        a: "Vantage is an AI deal engine. One agent per HubSpot deal. It monitors signals, scores deal health, generates drafted emails, and surfaces a prioritised action queue every morning. You execute the plan; the agent learns from what you do.",
      },
      {
        q: "What happens when I run agents?",
        a: "Running agents executes a 6-agent AI pipeline on your deals: Researcher, Risk Scanner, Grounding, Prioritiser, Drafter, and State Writer. It generates signals, MEDDPICC scores, and drafts. Costs ~$0.22/deal. Run it from the top bar for all urgent accounts or a single deal.",
      },
      {
        q: "How do I set up the platform?",
        a: "Four steps: (1) Connect HubSpot in Settings → Integrations and sync your deals. (2) Configure your product/ICP in Settings → Sales Intelligence. (3) Connect Outlook so you can send approved drafts. (4) Click Run Agents in the top bar to analyse your pipeline.",
      },
      {
        q: "Why are my drafts empty or missing?",
        a: "Drafts are generated when urgency score is above 0.7. If no drafts appear: run agents (the deal may not have been analysed yet), check that your Perplexity API key is set in Settings (it helps the agent detect signals), or lower the urgency threshold in Workspace settings.",
      },
    ],
  },
  {
    icon: ({ className }) => <Inbox className={className} />,
    title: "Agent Inbox",
    items: [
      {
        q: "What are the three tabs?",
        a: "Actions (your cross-deal action queue, overdue and today first), History (completed actions by week), and Pipeline (stage funnel with deal counts and health per stage, plus a full account browser).",
      },
      {
        q: "How does the action queue work?",
        a: "Actions are generated by the agent after each Sweep. Use 'Focus' mode to see your top 7 deals ranked by urgency × deal value. Click any card to open the detail panel. Mark Done, pick an outcome (Sent email / Had call / Got response), add notes. The agent uses your notes to plan the next step.",
      },
      {
        q: "What is the Focus / All toggle?",
        a: "Focus shows the top 7 actions by a composite score (urgency × deal value × overdue penalty). All shows every action due today or overdue. Start with Focus. If you're executing all 7, switch to All.",
      },
      {
        q: "What is the History tab?",
        a: "A cross-deal activity log of everything you've completed, grouped by week. Shows what you did, the outcome you logged, and the next action the agent generated. Also useful as a weekly rep performance view.",
      },
    ],
  },
  {
    icon: ({ className }) => <Eye className={className} />,
    title: "War Room",
    items: [
      {
        q: "What are the 4 tabs in the center panel?",
        a: "Act (action queue for this deal + draft review), Intel (AI Point of View, MEDDPICC scores, risk vectors, 3 Whys), History (full timeline of signals, interactions, calls, stage changes), Tools (Smart Fields, Plays, AI Fields, Training).",
      },
      {
        q: "How do I review and approve a draft?",
        a: "Go to the Act tab in the War Room, or click 'Review Draft' from an action card in the inbox. You'll see the full email with source citations. Approve as-is, edit and approve, or decline with a reason. Approved drafts can be sent as an Outlook draft or pushed to HubSpot.",
      },
      {
        q: "What does the red 'Fix →' button on MEDDPICC mean?",
        a: "Any MEDDPICC component below 35% shows in red with a 'Fix' button. Clicking it creates a targeted action in your queue for that gap, e.g. 'Identify Economic Buyer' for low EB score. The action appears in the queue immediately.",
      },
      {
        q: "What is the AI chat in the War Room?",
        a: "The right panel is an agent pre-seeded with this deal's context. Ask anything: 'Who is the most likely economic buyer based on call history?', 'Draft a re-engagement email for Ahmad', 'What are the main risks to this deal?'. Every answer cites its sources from the Gold Data layer.",
      },
    ],
  },
  {
    icon: ({ className }) => <BarChart3 className={className} />,
    title: "Analytics",
    items: [
      {
        q: "What is DAR and why does it matter?",
        a: "Draft Acceptance Rate. The % of AI-generated drafts the rep approved. Target is 60%+. Below 60% means the agent is generating off-target drafts. Check your ICP configuration in Settings. Above 80% is excellent.",
      },
      {
        q: "What is Execution Rate?",
        a: "Completed actions / generated actions, per week. This is the platform's north star metric. If it's below 30%, the agent is generating too many irrelevant actions. If it's above 60%, you're running a well-optimised pipeline.",
      },
      {
        q: "What does the Agent ROI metric show?",
        a: "LLM cost last 30 days divided by deals advanced or closed. E.g. '$2,400 in LLM costs → 12 deals advanced → $200/deal advanced'. Use this to justify the platform spend in quarterly reviews.",
      },
    ],
  },
  {
    icon: ({ className }) => <Settings className={className} />,
    title: "Settings & integrations",
    items: [
      {
        q: "How do I configure the AI to write in my voice?",
        a: "Settings → Voice Profile → Analyze. The platform reads your last ~1,500 sent emails and builds a writing fingerprint (tone, sentence length, sign-off style). The Drafter agent uses this profile for every email it generates.",
      },
      {
        q: "What is the ICP / Sales Intelligence section?",
        a: "This is where you tell the agent what you sell and who you sell to: product name, description, top differentiators, main competitors, ideal customer profile, and reference success stories. Without this, the agent uses generic Invigilo SafeKey defaults.",
      },
      {
        q: "How do I check if everything is connected correctly?",
        a: "Settings → Workspace Health (top of the settings page). It shows a score out of 100 and a checklist of what's missing, e.g. Perplexity API key, ICP not configured, voice profile not set. The status bar at the top of the inbox also shows a warning badge when health is below 80%.",
      },
      {
        q: "What does 'sync' vs 'connect' mean for HubSpot?",
        a: "Connect = authorise via OAuth (one-time). Sync = pull all deals from HubSpot into Vantage (do this after connecting, and again whenever HubSpot data drifts). After that, webhooks keep things in sync automatically when deals change.",
      },
    ],
  },
];

// ── Chat message type ─────────────────────────────────────────────────────────

interface ChatMsg {
  role: "user" | "assistant";
  content: string;
}

// ── Guide section component ───────────────────────────────────────────────────

function GuideSectionItem({ section }: { section: GuideSection }) {
  const [open, setOpen] = useState(false);
  const [expanded, setExpanded] = useState<number | null>(null);
  const Icon = section.icon;

  return (
    <div className="border border-zinc-100 rounded-xl overflow-hidden">
      <button
        onClick={() => setOpen(o => !o)}
        className="w-full flex items-center gap-2.5 px-4 py-3 hover:bg-zinc-50 transition-colors text-left"
      >
        <div className="w-6 h-6 rounded-lg bg-brand-50 flex items-center justify-center flex-shrink-0">
          <Icon className="w-3.5 h-3.5 text-brand-600" />
        </div>
        <span className="text-sm font-semibold text-zinc-800 flex-1">{section.title}</span>
        <span className="text-xs text-zinc-400 mr-1">{section.items.length}</span>
        {open
          ? <ChevronDown className="w-3.5 h-3.5 text-zinc-400 flex-shrink-0" />
          : <ChevronRight className="w-3.5 h-3.5 text-zinc-400 flex-shrink-0" />}
      </button>

      {open && (
        <div className="border-t border-zinc-100 divide-y divide-zinc-50">
          {section.items.map((item, i) => (
            <div key={i} className="px-4">
              <button
                onClick={() => setExpanded(prev => prev === i ? null : i)}
                className="w-full flex items-start gap-2 py-2.5 text-left"
              >
                <span className="text-xs font-medium text-zinc-700 flex-1 leading-relaxed">{item.q}</span>
                {expanded === i
                  ? <ChevronDown className="w-3 h-3 text-zinc-300 mt-0.5 flex-shrink-0" />
                  : <ChevronRight className="w-3 h-3 text-zinc-300 mt-0.5 flex-shrink-0" />}
              </button>
              {expanded === i && (
                <p className="text-xs text-zinc-500 leading-relaxed pb-3 pl-0">{item.a}</p>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

// ── Quick action chips ────────────────────────────────────────────────────────

const QUICK_QUESTIONS = [
  "How do I run agents?",
  "Why are there no drafts?",
  "How does the action queue work?",
  "What is the MEDDPICC score?",
  "How do I configure my ICP?",
  "What does Execution Rate mean?",
];

// ── Main component ────────────────────────────────────────────────────────────

export function HelpAssistant() {
  const [open, setOpen] = useState(false);
  const [tab, setTab] = useState<"guide" | "ask">("guide");
  const [messages, setMessages] = useState<ChatMsg[]>([]);
  const [input, setInput] = useState("");
  const [streaming, setStreaming] = useState(false);
  const [streamBuffer, setStreamBuffer] = useState("");
  const [search, setSearch] = useState("");
  const bottomRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const pathname = usePathname();

  useEffect(() => {
    if (bottomRef.current) {
      bottomRef.current.scrollIntoView({ behavior: "smooth" });
    }
  }, [messages, streamBuffer]);

  useEffect(() => {
    if (open && tab === "ask") {
      setTimeout(() => inputRef.current?.focus(), 100);
    }
  }, [open, tab]);

  const sendMessage = useCallback(async (msg: string) => {
    if (!msg.trim() || streaming) return;
    const q = msg.trim();
    setInput("");
    setMessages(prev => [...prev, { role: "user", content: q }]);
    setStreaming(true);
    setStreamBuffer("");
    setTab("ask");

    let full = "";
    try {
      for await (const chunk of streamHelpChat(q, pathname)) {
        if (chunk.type === "delta" && chunk.text) {
          full += chunk.text;
          setStreamBuffer(full);
        } else if (chunk.type === "done") {
          break;
        } else if (chunk.type === "error") {
          full = chunk.text ?? "Something went wrong. Please try again.";
          break;
        }
      }
      setMessages(prev => [...prev, { role: "assistant", content: full }]);
    } catch {
      setMessages(prev => [...prev, { role: "assistant", content: "Could not reach the assistant. Please try again." }]);
    } finally {
      setStreaming(false);
      setStreamBuffer("");
    }
  }, [streaming, pathname]);

  const filteredGuide = search
    ? GUIDE.map(section => ({
        ...section,
        items: section.items.filter(
          item =>
            item.q.toLowerCase().includes(search.toLowerCase()) ||
            item.a.toLowerCase().includes(search.toLowerCase())
        ),
      })).filter(s => s.items.length > 0)
    : GUIDE;

  return (
    <>
      {/* Floating help button */}
      <button
        onClick={() => setOpen(o => !o)}
        aria-label="Open help assistant"
        className={cn(
          "fixed bottom-5 right-5 z-[9999] w-11 h-11 rounded-full shadow-lg",
          "flex items-center justify-center transition-all duration-200",
          open
            ? "bg-zinc-800 text-white rotate-45"
            : "bg-brand-600 text-white hover:bg-brand-700 hover:scale-105"
        )}
      >
        {open ? <X className="w-5 h-5" /> : <HelpCircle className="w-5 h-5" />}
      </button>

      {/* Panel */}
      {open && (
        <>
          {/* Backdrop (mobile) */}
          <div
            className="fixed inset-0 z-40 bg-black/20 md:hidden"
            onClick={() => setOpen(false)}
          />

          <div
            className={cn(
              "fixed bottom-20 right-5 z-[9999]",
              "w-[420px] max-w-[calc(100vw-24px)]",
              "bg-white rounded-2xl shadow-2xl border border-zinc-200",
              "flex flex-col overflow-hidden",
              "transition-all duration-200",
            )}
            style={{ maxHeight: "calc(100vh - 100px)" }}
          >
            {/* Header */}
            <div className="px-5 pt-4 pb-3 border-b border-zinc-100 flex-shrink-0">
              <div className="flex items-center gap-2.5 mb-3">
                <div className="w-7 h-7 rounded-lg bg-brand-600 flex items-center justify-center flex-shrink-0">
                  <Zap className="w-4 h-4 text-white" />
                </div>
                <div>
                  <p className="text-sm font-bold text-zinc-900 leading-tight">Vantage Guide</p>
                  <p className="text-[10px] text-zinc-400">Platform support assistant</p>
                </div>
                <button
                  onClick={() => setOpen(false)}
                  className="ml-auto text-zinc-300 hover:text-zinc-600 transition-colors"
                >
                  <X className="w-4 h-4" />
                </button>
              </div>

              {/* Tab switcher */}
              <div className="flex gap-1 bg-zinc-100 rounded-lg p-0.5">
                <button
                  onClick={() => setTab("guide")}
                  className={cn(
                    "flex-1 flex items-center justify-center gap-1.5 py-1.5 rounded-md text-xs font-medium transition-colors",
                    tab === "guide"
                      ? "bg-white text-zinc-900 shadow-sm"
                      : "text-zinc-500 hover:text-zinc-700"
                  )}
                >
                  <BookOpen className="w-3 h-3" /> Guide
                </button>
                <button
                  onClick={() => { setTab("ask"); setTimeout(() => inputRef.current?.focus(), 100); }}
                  className={cn(
                    "flex-1 flex items-center justify-center gap-1.5 py-1.5 rounded-md text-xs font-medium transition-colors",
                    tab === "ask"
                      ? "bg-white text-zinc-900 shadow-sm"
                      : "text-zinc-500 hover:text-zinc-700"
                  )}
                >
                  <MessageSquare className="w-3 h-3" />
                  Ask
                  {messages.length > 0 && (
                    <span className="w-4 h-4 rounded-full bg-brand-600 text-white text-[9px] flex items-center justify-center font-bold">
                      {messages.filter(m => m.role === "assistant").length}
                    </span>
                  )}
                </button>
              </div>
            </div>

            {/* Guide tab */}
            {tab === "guide" && (
              <div className="flex-1 overflow-y-auto">
                {/* Search */}
                <div className="px-4 pt-3 pb-2 flex-shrink-0">
                  <div className="relative">
                    <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-zinc-300" />
                    <input
                      value={search}
                      onChange={e => setSearch(e.target.value)}
                      placeholder="Search help topics..."
                      className="w-full text-xs pl-8 pr-3 py-2 border border-zinc-200 rounded-lg focus:outline-none focus:border-brand-400 placeholder-zinc-300"
                    />
                    {search && (
                      <button
                        onClick={() => setSearch("")}
                        className="absolute right-3 top-1/2 -translate-y-1/2 text-zinc-300 hover:text-zinc-500"
                      >
                        <X className="w-3 h-3" />
                      </button>
                    )}
                  </div>
                </div>

                {/* Sections */}
                <div className="px-4 pb-4 space-y-2">
                  {filteredGuide.length === 0 ? (
                    <div className="py-8 text-center">
                      <p className="text-sm text-zinc-500">No results for "{search}"</p>
                      <button
                        onClick={() => { setSearch(""); sendMessage(search); }}
                        className="mt-2 text-xs text-brand-600 hover:text-brand-700 font-medium"
                      >
                        Ask the assistant instead →
                      </button>
                    </div>
                  ) : (
                    filteredGuide.map(section => (
                      <GuideSectionItem key={section.title} section={section} />
                    ))
                  )}
                </div>

                {/* Prompt to ask */}
                <div className="px-4 pb-4">
                  <button
                    onClick={() => setTab("ask")}
                    className="w-full flex items-center gap-2 px-4 py-3 border border-dashed border-brand-200 rounded-xl text-xs text-brand-600 hover:bg-brand-50 transition-colors"
                  >
                    <MessageSquare className="w-3.5 h-3.5 flex-shrink-0" />
                    Can't find what you need? Ask the assistant.
                  </button>
                </div>
              </div>
            )}

            {/* Ask tab */}
            {tab === "ask" && (
              <div className="flex flex-col flex-1 overflow-hidden">
                {/* Messages */}
                <div className="flex-1 overflow-y-auto px-4 py-3 space-y-3">
                  {messages.length === 0 && !streaming ? (
                    <div className="py-4">
                      <p className="text-xs font-semibold text-zinc-500 mb-2.5">Quick questions</p>
                      <div className="flex flex-wrap gap-1.5">
                        {QUICK_QUESTIONS.map(q => (
                          <button
                            key={q}
                            onClick={() => sendMessage(q)}
                            className="text-[11px] px-2.5 py-1 rounded-full border border-zinc-200 text-zinc-600 hover:border-brand-300 hover:text-brand-700 hover:bg-brand-50 transition-colors"
                          >
                            {q}
                          </button>
                        ))}
                      </div>
                    </div>
                  ) : (
                    messages.map((msg, i) => (
                      <div
                        key={i}
                        className={cn(
                          "flex",
                          msg.role === "user" ? "justify-end" : "justify-start"
                        )}
                      >
                        <div
                          className={cn(
                            "max-w-[88%] text-xs leading-relaxed rounded-2xl px-3.5 py-2.5",
                            msg.role === "user"
                              ? "bg-brand-600 text-white rounded-br-sm"
                              : "bg-zinc-100 text-zinc-800 rounded-bl-sm"
                          )}
                        >
                          {msg.content}
                        </div>
                      </div>
                    ))
                  )}

                  {/* Streaming message */}
                  {streaming && (
                    <div className="flex justify-start">
                      <div className="max-w-[88%] bg-zinc-100 text-zinc-800 text-xs leading-relaxed rounded-2xl rounded-bl-sm px-3.5 py-2.5">
                        {streamBuffer || (
                          <span className="flex items-center gap-1.5">
                            <span className="w-1 h-1 bg-zinc-400 rounded-full animate-bounce" style={{ animationDelay: "0ms" }} />
                            <span className="w-1 h-1 bg-zinc-400 rounded-full animate-bounce" style={{ animationDelay: "150ms" }} />
                            <span className="w-1 h-1 bg-zinc-400 rounded-full animate-bounce" style={{ animationDelay: "300ms" }} />
                          </span>
                        )}
                      </div>
                    </div>
                  )}

                  <div ref={bottomRef} />
                </div>

                {/* Input */}
                <div className="flex-shrink-0 px-4 pb-4 pt-2 border-t border-zinc-100">
                  <form
                    onSubmit={e => { e.preventDefault(); sendMessage(input); }}
                    className="flex gap-2"
                  >
                    <input
                      ref={inputRef}
                      value={input}
                      onChange={e => setInput(e.target.value)}
                      placeholder="Ask anything about Vantage..."
                      disabled={streaming}
                      className="flex-1 text-xs border border-zinc-200 rounded-xl px-3.5 py-2.5 focus:outline-none focus:border-brand-400 disabled:opacity-50 placeholder-zinc-400"
                    />
                    <button
                      type="submit"
                      disabled={!input.trim() || streaming}
                      className="flex-shrink-0 w-9 h-9 flex items-center justify-center bg-brand-600 text-white rounded-xl hover:bg-brand-700 disabled:opacity-40 transition-colors"
                    >
                      <Send className="w-3.5 h-3.5" />
                    </button>
                  </form>
                  <p className="text-[10px] text-zinc-300 mt-1.5 text-center">
                    Powered by Claude · Knows the Vantage platform
                  </p>
                </div>
              </div>
            )}
          </div>
        </>
      )}
    </>
  );
}
