"""Redis cache helpers — ASO caching for <50ms account state reads."""
import json
import logging
from typing import Optional
import redis.asyncio as aioredis
from app.config import get_settings

log = logging.getLogger(__name__)

_redis: Optional[aioredis.Redis] = None

ASO_PREFIX = "aso:"


async def get_redis() -> Optional[aioredis.Redis]:
    global _redis
    if _redis is None:
        try:
            settings = get_settings()
            _redis = aioredis.from_url(settings.redis_url, decode_responses=True)
        except Exception as e:
            log.warning(f"redis_init_failed: {e}")
    return _redis


async def _set(key: str, value: dict, ttl: int) -> None:
    r = await get_redis()
    if not r:
        return
    try:
        await r.setex(key, ttl, json.dumps(value, default=str))
    except Exception as e:
        log.debug(f"cache_set_failed key={key}: {e}")


async def _get(key: str) -> Optional[dict]:
    r = await get_redis()
    if not r:
        return None
    try:
        data = await r.get(key)
        return json.loads(data) if data else None
    except Exception:
        return None


async def _delete(key: str) -> None:
    r = await get_redis()
    if not r:
        return
    try:
        await r.delete(key)
    except Exception:
        pass


async def cache_aso(account_id: str, aso: dict, workspace_id: str = "") -> None:
    settings = get_settings()
    key = f"{ASO_PREFIX}{workspace_id}:{account_id}" if workspace_id else f"{ASO_PREFIX}{account_id}"
    await _set(key, aso, settings.redis_ttl_aso)


async def get_cached_aso(account_id: str, workspace_id: str = "") -> Optional[dict]:
    key = f"{ASO_PREFIX}{workspace_id}:{account_id}" if workspace_id else f"{ASO_PREFIX}{account_id}"
    return await _get(key)


async def invalidate_aso(account_id: str, workspace_id: str = "") -> None:
    key = f"{ASO_PREFIX}{workspace_id}:{account_id}" if workspace_id else f"{ASO_PREFIX}{account_id}"
    await _delete(key)


CTX_PREFIX = "ctx:"


async def cache_compressed_context(account_id: str, workspace_id: str, context: str) -> None:
    """Store pre-compressed assistant context for fast chat responses."""
    key = f"{CTX_PREFIX}{workspace_id}:{account_id}"
    r = await get_redis()
    if not r:
        return
    try:
        # TTL: 25 hours — regenerated by nightly pipeline
        await r.setex(key, 90000, context)
    except Exception as e:
        log.debug(f"ctx_cache_set_failed: {e}")


async def get_compressed_context(account_id: str, workspace_id: str) -> Optional[str]:
    """Retrieve pre-compressed assistant context. Returns None if not cached."""
    key = f"{CTX_PREFIX}{workspace_id}:{account_id}"
    r = await get_redis()
    if not r:
        return None
    try:
        return await r.get(key)
    except Exception:
        return None
