"""Move rules-engine placeholder drafts out of the approvable queue.

Placeholders ("[Auto-generated by rule ...]") were created with
status='pending', which made literal placeholder text approvable and
pushable to Outlook. They are now created as status='queued'; migrate
the existing ones.

Revision ID: 20260610_0012
Revises: 20260610_0011
Create Date: 2026-06-10
"""
from alembic import op

revision = '20260610_0012'
down_revision = '20260610_0011'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        UPDATE drafts
        SET status = 'queued'
        WHERE status = 'pending'
          AND content LIKE '[Auto-generated by rule%'
        """
    )


def downgrade() -> None:
    op.execute(
        """
        UPDATE drafts
        SET status = 'pending'
        WHERE status = 'queued'
          AND content LIKE '[Auto-generated by rule%'
        """
    )
